version: '3'

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
        - .env.local

  mongo:
    image: mongo:5.0.8-focal
    ports:
      - '27018:27017'
    env_file:
        - .env.local
    volumes:
        - mongodata:/data/db

volumes:
  mongodata: