version: '3'

services:
  node:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3033:3000'
    depends_on:
      - mongo
      - redis
    links:
      - mongo
    env_file:
        - .env.local

  mongo:
    image: mongo:5.0.8-focal
    ports:
      - '27017:27017'
    env_file:
        - .env.local
    volumes:
        - mongodata:/data/db

  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - '6379:6379'

volumes:
  mongodata:
